(define (domain cube)
	(:requirements :strips :equality :typing)
	(:types color)
	(:predicates 
		(cube1 ?x ?y ?z -color)
		(cube2 ?x ?y ?z -color)
		(cube3 ?x ?y ?z -color)
		(cube4 ?x ?y ?z -color)
		(cube5 ?x ?y ?z -color)
		(cube6 ?x ?y ?z -color)
		(cube7 ?x ?y ?z -color)
		(cube8 ?x ?y ?z -color)
	)
	
	(:action Right
		:parameters ()
		:effect 
			(and
				(forall(?x ?y ?z -color)
					(when(cube1 ?x ?y ?z)
						(and
							(not(cube1 ?x ?y ?z))
							(cube2 ?x ?y ?z)
						)
					)
				)	
				(forall(?x ?y ?z -color)
					(when(cube2 ?x ?y ?z)
						(and
							(not(cube2 ?x ?y ?z))
							(cube5 ?x ?y ?z)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube5 ?x ?y ?z)
						(and
							(not(cube5 ?x ?y ?z))
							(cube6 ?x ?y ?z)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube6 ?x ?y ?z)
						(and
							(not(cube6 ?x ?y ?z))
							(cube1 ?x ?y ?z)
						)
					)
				)
			)
			
	)

	(:action Left
		:parameters ()
		:effect 
			(and
				(forall(?x ?y ?z -color)
					(when(cube1 ?x ?y ?z)
						(and
							(not(cube1 ?x ?y ?z))
							(cube6 ?x ?y ?z)
						)
					)
				)	
				(forall(?x ?y ?z -color)
					(when(cube6 ?x ?y ?z)
						(and
							(not(cube6 ?x ?y ?z))
							(cube5 ?x ?y ?z)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube5 ?x ?y ?z)
						(and
							(not(cube5 ?x ?y ?z))
							(cube2 ?x ?y ?z)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube2 ?x ?y ?z)
						(and
							(not(cube2 ?x ?y ?z))
							(cube1 ?x ?y ?z)
						)
					)
				)
			)
	)
	(:action Up
		:parameters ()
		:effect 
			(and
				(forall(?x ?y ?z -color)
					(when(cube2 ?x ?y ?z)
						(and
							(not(cube2 ?x ?y ?z))
							(cube5 ?y ?z ?x)
						)
					)
				)	
				(forall(?x ?y ?z -color)
					(when(cube5 ?x ?y ?z)
						(and
							(not(cube5 ?x ?y ?z))
							(cube7 ?x ?z ?y)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube7 ?x ?y ?z)
						(and
							(not(cube7 ?x ?y ?z))
							(cube4 ?z ?x ?y)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube4 ?x ?y ?z)
						(and
							(not(cube4 ?x ?y ?z))
							(cube2 ?z ?y ?x)
						)
					)
				)
			)
	)
	(:action Down
		:parameters ()
		:effect 
			(and
				(forall(?x ?y ?z -color)
					(when(cube2 ?x ?y ?z)
						(and
							(not(cube2 ?x ?y ?z))
							(cube4 ?z ?y ?x)
						)
					)
				)	
				(forall(?x ?y ?z -color)
					(when(cube4 ?x ?y ?z)
						(and
							(not(cube4 ?x ?y ?z))
							(cube7 ?y ?z ?x)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube7 ?x ?y ?z)
						(and
							(not(cube7 ?x ?y ?z))
							(cube5 ?x ?z ?y)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube5 ?x ?y ?z)
						(and
							(not(cube5 ?x ?y ?z))
							(cube2 ?z ?x ?y)
						)
					)
				)
			)
			
	)
	(:action CW
		:parameters ()
		:effect 
			(and
				(forall(?x ?y ?z -color)
					(when(cube1 ?x ?y ?z)
						(and
							(not(cube1 ?x ?y ?z))
							(cube2 ?y ?z ?x)
						)
					)
				)	
				(forall(?x ?y ?z -color)
					(when(cube2 ?x ?y ?z)
						(and
							(not(cube2 ?x ?y ?z))
							(cube4 ?x ?z ?y)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube4 ?x ?y ?z)
						(and
							(not(cube4 ?x ?y ?z))
							(cube3 ?z ?x ?y)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube3 ?x ?y ?z)
						(and
							(not(cube3 ?x ?y ?z))
							(cube1 ?z ?y ?x)
						)
					)
				)
			)
	)
	(:action AW
		:parameters ()
		:effect 
			(and
				(forall(?x ?y ?z -color)
					(when(cube1 ?x ?y ?z)
						(and
							(not(cube1 ?x ?y ?z))
							(cube3 ?z ?y ?x)
						)
					)
				)	
				(forall(?x ?y ?z -color)
					(when(cube3 ?x ?y ?z)
						(and
							(not(cube3 ?x ?y ?z))
							(cube4 ?y ?z ?x)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube4 ?x ?y ?z)
						(and
							(not(cube4 ?x ?y ?z))
							(cube2 ?x ?z ?y)
						)
					)
				)
				(forall(?x ?y ?z -color)
					(when(cube2 ?x ?y ?z)
						(and
							(not(cube2 ?x ?y ?z))
							(cube1 ?z ?x ?y)
						)
					)
				)
			)
	)
)